# numpy教程1_array

### 1、array
在NumPy中维度(dimension)叫做轴(axis),轴的个数叫做秩(rank)

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = np.array(a)
type(b)

numpy.ndarray

In [3]:
print b.shape  
print b.argmax()
print b.max()  
print b.mean()
print b.ndim
print b.size
print b.dtype
print b.itemsize
print b.data # 一般不使用

(4,)
3
4
2.5
1
4
int64
8



数组创建

In [4]:
np.array([[1,2],[3,4]],dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [5]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
np.zeros((3,4),dtype = np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [7]:
np.empty((2,3))  # 内容随机

array([[  6.90597881e-310,   6.90597881e-310,   4.72327548e-317],
       [  6.90596914e-310,   6.90596914e-310,   6.90596914e-310]])

In [8]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [10]:
np.linspace(0,6,5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

保存数据到文件

In [12]:
p = np.array([
    [0,1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])

In [13]:
#with open('./p.npy', 'w') as f:
np.save('p.npy',p)
#with open('./p.npy','w') as f:
q=np.load('p.npy')

维度变换

In [14]:
a = np.arange(24).reshape((2,3,4))
print a

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
a[:,2,:]  # :表示当前维茺上所有下标

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [16]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [17]:
a[...,1] # ...表示没有明确指出的维度

array([[ 1,  5,  9],
       [13, 17, 21]])

In [18]:
a[:,1:,1:-1]

array([[[ 5,  6],
        [ 9, 10]],

       [[17, 18],
        [21, 22]]])

In [19]:
a[-1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
np.split(np.arange(9),[2,6])

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8])]

In [21]:
np.split(np.arange(9),3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

vstack是指沿着纵轴拼接两个array，vertical
hstack是指沿着横轴拼接两个array，horizontal
更广义的拼接用concatenate实现，horizontal后的两句依次等效于vstack和hstack
stack不是拼接而是在输入array的基础上增加一个新的维度

In [22]:
np.vstack((10,11))

array([[10],
       [11]])

In [23]:
np.hstack([10,11])

array([10, 11])

In [24]:
np.concatenate([[10,11],[1,2]],axis=-1)

array([10, 11,  1,  2])

In [25]:
np.stack([10,11])

array([10, 11])

转置

In [26]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])

In [27]:
a.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [28]:
np.rot90(a,1)  # 逆时针旋转90度，每二个参数为次数

array([[ 3,  6,  9, 12],
       [ 2,  5,  8, 11],
       [ 1,  4,  7, 10]])

In [29]:
np.fliplr(a)  # 沿纵轴左右翻转

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [30]:
np.flipud(a)  # 沿横轴上五翻转

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [31]:
np.roll(a,1) # 按照一维顺序滚动位移,后面的参数滚动的个数

array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
np.roll(a,1,axis=1) # 按照指定轴滚动位移

array([[ 3,  1,  2],
       [ 6,  4,  5],
       [ 9,  7,  8],
       [12, 10, 11]])

基础数学

In [33]:
np.abs(-1)

1

In [34]:
np.sin(np.pi/2)

1.0

In [35]:
np.arctanh(0.46218)

0.50007991002851626

In [36]:
np.exp(3)  # e为底的指数函数

20.085536923187668

In [37]:
np.power(2,3)

8

In [38]:
np.dot([1,2],[3,4])

11

In [39]:
np.sqrt(25)

5.0

In [40]:
np.sum([1,2,3,4])

10

In [41]:
np.mean([4,5,6,7])

5.5

In [42]:
np.std([1,2,3,2,1,4,3,2,0]) # 标准差

1.1547005383792515

对于array，默认执行对位运算。涉及到多个array的对位运算需要array的维度一致，如果一个array的维度和另一个array的子维度一致，则在没有对齐的维度上分别执行对位运算，这种机制叫做广播（broadcasting），言语解释比较难，还是看例子理解：

In [43]:
a = np.array([
    [1,2,3],
    [4,5,6]])
b = np.array([
    [1,2,3],
    [1,2,3]])

In [44]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [45]:
a-b

array([[0, 0, 0],
       [3, 3, 3]])

In [46]:
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [47]:
a**b

array([[  1,   4,  27],
       [  4,  25, 216]])

In [48]:
a/b

array([[1, 1, 1],
       [4, 2, 2]])

In [49]:
c=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
d = np.array([2,2,2])

In [50]:
c+d

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])